export { default as Contact } from './Contact'
export { default as Setting } from './Setting'
export { default as Follow } from './Follow'
export { default as Favorite } from './Favorite'
export { default as MenuHome } from './Home'
export { default as Contribute } from './Contribute'
export { default as History } from './History'
export { default as Questionaire } from './Questionaire'
